# Generated by Django 2.2.7 on 2021-07-14 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=40)),
                ('lname', models.CharField(max_length=20)),
                ('emai', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'registratn',
            },
        ),
    ]
