# Generated by Django 2.2.7 on 2021-07-14 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogsite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='admin_status',
            field=models.CharField(default='Not Approved', max_length=20),
        ),
    ]
