# Generated by Django 2.2.7 on 2021-07-14 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogsite', '0002_registration_admin_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='fname',
            field=models.CharField(max_length=500),
        ),
    ]
