# Generated by Django 2.2.7 on 2021-07-14 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogsite', '0003_auto_20210714_1223'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='blog',
            field=models.CharField(default='Null', max_length=500),
        ),
        migrations.AlterField(
            model_name='registration',
            name='fname',
            field=models.CharField(max_length=40),
        ),
    ]
