# Generated by Django 2.2.7 on 2021-07-14 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogsite', '0004_auto_20210714_1240'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emai', models.CharField(max_length=20)),
                ('blog', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'blog',
            },
        ),
    ]
