# Generated by Django 2.2.7 on 2021-07-14 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogsite', '0005_blob'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Blob',
            new_name='Blog',
        ),
    ]
