# Generated by Django 2.2.7 on 2021-07-15 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogsite', '0007_blog_subjct'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='likes',
            field=models.CharField(default=0, max_length=500),
        ),
    ]
